services:

  # envoy, configured as with envoy.yaml to use extprocs
  envoy:
    image: envoyproxy/envoy:${ENVOY_VERSION:-v1.22-latest}
    ports:
      - "8080:8000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  # upstream "echo" server
  upstream:
    hostname: upstream
    image: echo-server:${IMAGE_TAG:-compose}
    build:
      context: _mocks/echo
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - LOG_LEVEL=info

  # extprocs
  noop:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - noop
  trivial:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - trivial
  timer:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - timer
  data:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - data
  digest:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - digest
  dedup:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - dedup
  masker:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - masker
  echo:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - echo
